name: Deploy static files to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Діагностика файлової системи (для дебагу)
      - name: Debug file tree
        run: |
          echo "=== Корінь репозиторію ==="
          ls -1
          echo "=== Вміст .github/workflows ==="
          ls -1 .github/workflows

      # 3. Завантаження артефакту для GitHub Pages (весь корінь)
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./

      # 4. Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
